# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"5\n\x0f\x42inaryOperation\x12\x10\n\x08operand1\x18\x01 \x01(\x05\x12\x10\n\x08operand2\x18\x02 \x01(\x05\"\'\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x81\x02\n\nCalculator\x12\x38\n\x03\x41\x64\x64\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.Result\"\x00\x12=\n\x08Subtract\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.Result\"\x00\x12=\n\x08Multiply\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.Result\"\x00\x12;\n\x06\x44ivide\x12\x1b.calculator.BinaryOperation\x1a\x12.calculator.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYOPERATION']._serialized_start=32
  _globals['_BINARYOPERATION']._serialized_end=85
  _globals['_RESULT']._serialized_start=87
  _globals['_RESULT']._serialized_end=126
  _globals['_CALCULATOR']._serialized_start=129
  _globals['_CALCULATOR']._serialized_end=386
# @@protoc_insertion_point(module_scope)
